// 다운로드 웹과 앱에서 함께 사용하는 한·영 문구.
export const RELEASE_COPY = {
  'release.getStarted':['시작하기','GET STARTED'],
  'release.releaseNotes':['릴리스 안내','RELEASE NOTES'],
  'release.downloads':['설치 파일','Downloads'],
  'release.eyebrow':['AOA 다운로드','DOWNLOAD AOA'],
  'release.title':['24시간 불이 꺼지지 않는\nAI 사무실','An AI office\nthat never sleeps'],
  'release.lead':['직원을 구성하고, 회사 지식을 연결하고, 업무를 맡기세요. 내 컴퓨터에서 시작하는 Atomy Office Agent.','Build your team, connect company knowledge, and delegate work. Start with Atomy Office Agent on your computer.'],
  'release.loading':['최신 릴리스를 확인하고 있습니다.','Checking the latest release.'],
  'release.unpublished':['첫 설치 버전을 준비하고 있습니다.','The first release is being prepared.'],
  'release.failed':['릴리스 정보를 가져오지 못했습니다. 릴리스 기록에서 확인해 주세요.','Release information is unavailable. Please check the release history.'],
  'release.preparing':['준비 중','Coming soon'],
  'release.download':['다운로드','Download'],
  'release.silicon':['Apple 칩을 사용하는 Mac','For Mac with an Apple chip'],
  'release.windows':['64비트 Intel·AMD PC','For 64-bit Intel and AMD PCs'],
  'release.guideTitle':['내 사무실을 시작하는 방법','Start your office'],
  'release.step1':['컴퓨터에 맞는 파일 받기','Choose your installer'],
  'release.step1Body':['Mac 설치 파일은 Apple 칩(M 시리즈) 모델용입니다. Windows는 위의 x64 설치 파일을 선택하세요.','The Mac installer is for Apple silicon (M-series) models. On Windows, choose the x64 installer above.'],
  'release.step2':['설치하고 사무실 열기','Install and open your office'],
  'release.step2Body':['Mac은 DMG를 열어 앱을 응용 프로그램 폴더에 옮깁니다. Windows는 설치 프로그램의 안내를 따릅니다.','On Mac, open the DMG and move the app to Applications. On Windows, follow the installer instructions.'],
  'release.step3':['AI 연결 후 직원에게 업무 맡기기','Connect AI and delegate work'],
  'release.step3Body':['설정에서 사용할 AI를 연결하세요. 이후 업데이트는 앱의 상단 버튼이나 설정에서 확인할 수 있습니다.','Connect your AI in Settings. Future updates are available from the top bar or Settings in the app.'],
  'release.notesTitle':['새롭게 달라진 점','What’s new'],
  'release.notesEmpty':['게시된 릴리스의 변경 사항이 여기에 표시됩니다.','Published release notes will appear here.'],
  'release.history':['전체 릴리스 기록 보기 ↗','View release history ↗'],
  'release.footer':['회사 지식과 사용자 데이터는 이 페이지에 게시하지 않습니다.','Company knowledge and user data are not published on this page.'],
  "release.launchTitle":["설치·첫 실행 가이드", "Installation & first launch"],
  "release.launchIntro":["현재 Mac은 Apple 서명·공증, Windows는 코드 서명을 준비 중입니다. 서명이나 다운로드 평판이 부족하면 경고가 나타날 수 있지만, 모든 경고가 미서명 때문인 것은 아닙니다. 이 페이지에서 연결한 공식 GitHub 설치 파일인지 먼저 확인하세요.", "Apple signing/notarization and Windows code signing are pending. Missing signatures or download reputation can trigger warnings, but not every warning is caused by signing. First verify that the installer came from the official GitHub release linked on this page."],
  "release.macGuide":["Mac · 앱이 열리지 않을 때", "Mac · When the app cannot be opened"],
  "release.mac1":["DMG를 열고 Atomy Office Agent를 응용 프로그램 폴더에 옮긴 뒤, 앱을 한 번 실행합니다.", "Open the DMG, move Atomy Office Agent to Applications, then try opening it once."],
  "release.mac2":["개발자를 확인할 수 없거나 Apple이 악성 소프트웨어 여부를 확인할 수 없다는 알림이면 ‘완료’를 누릅니다.", "If the alert says the developer cannot be verified or Apple cannot check the app for malware, select Done."],
  "release.mac3":["시스템 설정 → 개인정보 보호 및 보안 → 보안에서 Atomy Office Agent 옆의 ‘그래도 열기’를 누릅니다.", "Go to System Settings → Privacy & Security → Security, then select Open Anyway for Atomy Office Agent."],
  "release.mac4":["요청되면 Mac 암호 또는 Touch ID로 인증하고 ‘열기’를 누릅니다. 이후에는 응용 프로그램에서 실행할 수 있습니다.", "Authenticate with your Mac password or Touch ID if requested, then select Open. You can launch it from Applications afterward."],
  "release.windowsGuide":["Windows · 설치 실행이 차단될 때", "Windows · When the installer is blocked"],
  "release.windows1":["다운로드한 설치 파일을 실행합니다. ‘Windows의 PC 보호’ 화면이 나오면 ‘추가 정보’를 누릅니다.", "Run the downloaded installer. If Windows protected your PC appears, select More info."],
  "release.windows2":["공식 배포 파일인지 확인한 뒤 ‘실행’을 누르고 설치 안내를 따릅니다.", "After verifying the installer is from the official release, select Run anyway and follow the installer."],
  "release.windows3":["‘실행’이 없거나 회사 정책·스마트 앱 컨트롤로 차단되면 관리자에게 문의하세요. 보안 기능 전체를 끌 필요는 없습니다.", "If Run anyway is unavailable or an organization policy or Smart App Control blocks installation, contact your administrator. Do not disable system-wide protection."],
  "release.edgeGuide":["Edge · 다운로드 경고가 나타날 때", "Edge · Download warnings"],
  "release.edge1":["오른쪽 위 다운로드 목록에서 해당 파일의 경고를 확인합니다. ‘일반적으로 다운로드되지 않습니다’ 같은 평판 경고인지 살펴보세요.", "Open Downloads at the top right and inspect the warning for the file, such as a notice that it is not commonly downloaded."],
  "release.edge2":["공식 파일임을 확인한 경우 파일의 ⋯ → 유지 → 더 보기 → 그래도 계속을 선택합니다. 버전에 따라 ‘유지’ 또는 ‘계속 유지’로 표시될 수 있습니다.", "For a verified official file, choose its ⋯ menu → Keep → Show more → Keep anyway. Available labels and options vary by version."],
  "release.chromeGuide":["Chrome · 다운로드 경고가 나타날 때", "Chrome · Download warnings"],
  "release.chrome1":["오른쪽 위 다운로드 아이콘 또는 ⋮ → 다운로드에서 차단된 파일의 경고 사유를 확인합니다.", "Open the Downloads icon at the top right, or ⋮ → Downloads, and review why the file was blocked."],
  "release.chrome2":["검사 옵션이 있으면 먼저 검사합니다. 일반적이지 않거나 잘 알려지지 않은 파일이라는 경고이고, 공식 파일임을 확인한 뒤 계속 받기로 결정한 경우에만, 해당 파일의 상세 메뉴에서 ‘계속 다운로드’ 또는 ‘위험한 파일 다운로드’처럼 표시되는 항목을 선택합니다. 문구·선택 가능 여부는 경고와 버전에 따라 다릅니다.", "Use the scan option first if offered. Only for an uncommon or unfamiliar file warning, if you verify the official file and decide to proceed, open its warning details and use the offered option such as Keep or Download suspicious file. Labels and availability vary by warning and version."],
  "release.launchHelp":["악성코드·바이러스 탐지, 파일 손상 경고는 위 절차로 넘기지 말고 다운로드를 중단한 뒤 문의해 주세요. 버튼이 없거나 계속 차단되면 경고 문구와 OS·브라우저 버전을 suhwang@atomypark.com으로 보내 주세요.", "For malware, virus, or file-damage warnings, stop and contact us instead of bypassing them. If an option is missing or blocking continues, send the warning text and OS/browser versions to suhwang@atomypark.com."],
  "release.appleHelp":["Apple 공식 안내 ↗", "Apple guidance ↗"],
  "release.chromeHelp":["Chrome 공식 안내 ↗", "Chrome guidance ↗"],
  "release.windowsHelp":["Windows 공식 안내 ↗", "Windows guidance ↗"],
};
