// 다운로드 웹과 앱에서 함께 사용하는 한·영 문구.
export const RELEASE_COPY = {
  'release.getStarted':['시작하기','GET STARTED'],
  'release.releaseNotes':['릴리스 안내','RELEASE NOTES'],
  'release.downloads':['설치 파일','Downloads'],
  'release.eyebrow':['AOA 다운로드','DOWNLOAD AOA'],
  'release.title':['24시간 불이 꺼지지 않는\nAI 사무실','An AI office\nthat never sleeps'],
  'release.lead':['직원을 구성하고, 회사 지식을 연결하고, 업무를 맡기세요. 내 컴퓨터에서 시작하는 Atomy Office Agent.','Build your team, connect company knowledge, and delegate work. Start with Atomy Office Agent on your computer.'],
  'release.loading':['최신 릴리스를 확인하고 있습니다.','Checking the latest release.'],
  'release.unpublished':['첫 설치 버전을 준비하고 있습니다.','The first release is being prepared.'],
  'release.failed':['릴리스 정보를 가져오지 못했습니다. 릴리스 기록에서 확인해 주세요.','Release information is unavailable. Please check the release history.'],
  'release.preparing':['준비 중','Coming soon'],
  'release.download':['다운로드','Download'],
  'release.silicon':['Apple 칩을 사용하는 Mac','For Mac with an Apple chip'],
  'release.intel':['Intel 프로세서를 사용하는 Mac','For Mac with an Intel processor'],
  'release.windows':['64비트 Intel·AMD PC','For 64-bit Intel and AMD PCs'],
  'release.guideTitle':['내 사무실을 시작하는 방법','Start your office'],
  'release.step1':['컴퓨터에 맞는 파일 받기','Choose your installer'],
  'release.step1Body':['Mac은 Apple 메뉴의 ‘이 Mac에 관하여’에서 칩을 확인하세요. Windows는 위의 x64 설치 파일을 선택하세요.','On Mac, check the chip in About This Mac. On Windows, choose the x64 installer above.'],
  'release.step2':['설치하고 사무실 열기','Install and open your office'],
  'release.step2Body':['Mac은 DMG를 열어 앱을 응용 프로그램 폴더에 옮깁니다. Windows는 설치 프로그램의 안내를 따릅니다.','On Mac, open the DMG and move the app to Applications. On Windows, follow the installer instructions.'],
  'release.step3':['AI 연결 후 직원에게 업무 맡기기','Connect AI and delegate work'],
  'release.step3Body':['설정에서 사용할 AI를 연결하세요. 이후 업데이트는 앱의 상단 버튼이나 설정에서 확인할 수 있습니다.','Connect your AI in Settings. Future updates are available from the top bar or Settings in the app.'],
  'release.notesTitle':['새롭게 달라진 점','What’s new'],
  'release.notesEmpty':['게시된 릴리스의 변경 사항이 여기에 표시됩니다.','Published release notes will appear here.'],
  'release.history':['전체 릴리스 기록 보기 ↗','View release history ↗'],
  'release.footer':['회사 지식과 사용자 데이터는 이 페이지에 게시하지 않습니다.','Company knowledge and user data are not published on this page.'],
};
